### ISSUE TITLE
getting getHeaderName() must returning of type string , null returned 

### ISSUE THREAD

**Issue by kamarajuPrathi** [ajaaleixo/laravel-middleware-correlation-id#1]
I am trying to use this middleware and added to routes , i get this error .

its gives error at correlationId.php line 23 .

can you let me know how can we get rid of it

**Comment by ajaaleixo** [comment]
Hi
which version of laravel are you running?

**Comment by ajaaleixo** [comment]
@kamarajuPrathi please check if you published your config file. If not, please do (or just copy the content from this package and parte it under config/correlationid.php.

If you have done this, confirm if there is a correlationid.header_name setting. That settings is the header name where you want to save the correlationId.

**Comment by ajaaleixo** [comment]
@kamarajuPrathi anyway I could provide more assistance?

**Comment by ajaaleixo** [comment]
@kamarajuPrathi I'm gonna close this issue as no answer was provided to troubleshoot.
Thanks
